export { default as Home } from "./Home";
export { default as Matches } from "./Matches";
export { default as Messages } from "./Messages";
export { default as Profile } from "./Profile";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as HomeScreen } from "./HomeScreen";
export { default as ResetPassword } from "./ResetPassword";
export { default as MyProfile } from "./MyProfile";
